[package]
name = "geom_bench"
version = "0.0.1"
authors = ["Nicolas Silva <nical@fastmail.com>"]
workspace = "../.."

[[bin]]
name = "geom_bench"

[dependencies]
lyon = { path = "../../crates/lyon" }
bencher = "0.1.1"
