[package]
name = "Fill tessellator benchmark"
version = "0.0.1"
authors = ["Nicolas Silva <nical@fastmail.com>"]
workspace = "../.."

[[bin]]
name = "fill_bench"
path = "src/fill_bench.rs"

[dependencies]
lyon = { path = "../../" }
bencher = "0.1.1"
