[package]
name = "wgpu-advanced-example"
version = "0.1.0"
authors = ["Nicolas Silva <nical@fastmail.com>"]
workspace = "../.."
edition = "2018"

[[bin]]
name = "wgpu_advanced"
path = "src/main.rs"

[dependencies]
lyon = { path = "../../", features = ["extra"] }

wgpu = "0.2.3"
wgpu-native = "0.2.7"

[features]
default = []
local = ["wgpu-native/local"]
metal = ["wgpu/metal"]
dx11 = ["wgpu/dx11"]
dx12 = ["wgpu/dx12"]
vulkan = ["wgpu/vulkan"]
