[package]
name = "intersections-example"
version = "0.1.0"
authors = ["Nicolas Silva <nical@fastmail.com>"]
workspace = "../.."

[[bin]]
name = "intersections"
path = "src/main.rs"

[dependencies]
lyon = { path = "../../" }

gfx = "0.17.1"
gfx_device_gl = "0.15.0"
gfx_window_glutin = "0.28.0"
glutin = "0.19.0"
