[package]
name = "lyon_path"
version = "1.0.4"
description = "Types and utilities to store, build and iterate over 2D paths."
authors = ["Nicolas Silva <nical@fastmail.com>"]
repository = "https://github.com/nical/lyon"
documentation = "https://docs.rs/lyon_path/"
license = "MIT OR Apache-2.0"
workspace = "../.."
edition = "2018"

[lib]
name = "lyon_path"

[features]
default = ["std"]
std = ["lyon_geom/std", "num-traits/std"]
serialization = ["serde", "lyon_geom/serialization"]

[dependencies]
lyon_geom = { version = "1.0.4", path = "../geom", default-features = false }
num-traits = { version = "0.2.15", default-features = false, features = ["libm"] }
serde = { version = "1.0", optional = true, features = ["serde_derive"], default-features = false }
