[package]
name = "lyon_renderer"
version = "0.8.0"
description = "High level APIs on top of lyon and gfx-rs."
authors = ["Nicolas Silva <nical@fastmail.com>"]
repository = "https://github.com/nical/lyon"
documentation = "https://docs.rs/lyon_renderer/"
keywords = ["2d", "graphics", "tessellation"]
license = "MIT/Apache-2.0"

[dependencies]
gfx = "0.16"
gfx_device_gl = "0.14"
lyon_path = { version = "0.8.0", path = "../path" }
lyon_geom = { version = "0.8.0", path = "../geom" }
lyon_tessellation = { version = "0.8.0", path = "../tessellation" }
