[package]
name = "lyon_renderer"
version = "0.7.0"
description = "High level APIs on top of lyon and gfx-rs."
authors = ["Nicolas Silva <nical@fastmail.com>"]
repository = "https://github.com/nical/lyon"
documentation = "https://docs.rs/lyon_renderer/"
keywords = ["2d", "graphics", "tessellation"]
license = "MIT/Apache-2.0"

[dependencies]
lyon_core = { version = "0.7.0", path = "../core" }
lyon_path = { version = "0.7.0", path = "../path" }
lyon_bezier = { version = "0.7.0", path = "../bezier" }
lyon_tessellation = { version = "0.7.0", path = "../tessellation" }
lyon_path_builder = { version = "0.7.0", path = "../path_builder" }
lyon_path_iterator = { version = "0.7.0", path = "../path_iterator" }
gl = "0.6.3"
